---
abstract: 'Log headers and body of HTTP traffic'
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
build_requires:
  Test::More: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-TrafficLog
provides:
  Plack::Middleware::TrafficLog:
    file: lib/Plack/Middleware/TrafficLog.pm
    version: '0.0400'
requires:
  POSIX::strftime::Compiler: '0'
  Plack: '0'
  perl: '5.008'
resources:
  bugtracker: http://github.com/dex4er/perl-Plack-Middleware-TrafficLog/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/dex4er/perl-Plack-Middleware-TrafficLog
version: '0.0400'
